"""initial

Revision ID: 63129e15aaac
Revises: 
Create Date: 2023-09-12 15:28:18.662706

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63129e15aaac'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_product', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('marca', sa.String(), nullable=False),
    sa.Column('description', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id_product', name='pk_products')
    )
    op.create_index(op.f('ix_products_created_at'), 'products', ['created_at'], unique=False)
    op.create_index(op.f('ix_products_id_product'), 'products', ['id_product'], unique=False)
    op.create_table('users',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_user', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name_user', sa.String(length=30), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_user', name='pk_users')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id_user'), 'users', ['id_user'], unique=False)
    op.create_table('favorites',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('id_favorite', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_user', sa.Integer(), nullable=True),
    sa.Column('id_product', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_product'], ['products.id_product'], ),
    sa.ForeignKeyConstraint(['id_user'], ['users.id_user'], ),
    sa.PrimaryKeyConstraint('id_favorite', name='pk_favorites')
    )
    op.create_index(op.f('ix_favorites_created_at'), 'favorites', ['created_at'], unique=False)
    op.create_index(op.f('ix_favorites_id_favorite'), 'favorites', ['id_favorite'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_favorites_id_favorite'), table_name='favorites')
    op.drop_index(op.f('ix_favorites_created_at'), table_name='favorites')
    op.drop_table('favorites')
    op.drop_index(op.f('ix_users_id_user'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_products_id_product'), table_name='products')
    op.drop_index(op.f('ix_products_created_at'), table_name='products')
    op.drop_table('products')
    # ### end Alembic commands ###
